name: build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build dist
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Install Go
        uses: actions/setup-go@v2
        
      - name: Install statik
        run: go get github.com/rakyll/statik
        
      - name: Build embed files
        run: statik -src=dist
