name: build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build for production
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Install Go
        uses: actions/setup-go@v2
        
      - name: Install statik & build embed files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/rakyll/statik
          statik -src=dist
